version: '3.9'
services:
  dbadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"

  db:
    image: postgres:14.4
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5432:5432"

  # web:
  #  image: odoo:15.0
  #  depends_on:
  #    - db
  #  ports:
  #    - "8069:8069"
  #  volumes:
  #    - ./:/mnt/extra-addons
  #  environment:
  #    - HOST=db
  #    - USER=odoo
  #    - PASSWORD=admin